# Inicio

RX COVID F

In [ ]:
https://drive.google.com/file/d/1Mqil6GvXximtQyFy1Ie7F8OEga7pjYrT/view?usp=sharing

In [ ]:
!wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1Mqil6GvXximtQyFy1Ie7F8OEga7pjYrT' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1Mqil6GvXximtQyFy1Ie7F8OEga7pjYrT" -O archivo.zip && rm -rf /tmp/cookies.txt
!unzip archivo.zip

Se truncaron las últimas líneas 5000 del resultado de transmisión.
  inflating: volumes/patient_159/Axial/I00040.JPG  
  inflating: volumes/patient_159/Axial/I00035.JPG  
  inflating: volumes/patient_159/Axial/I00039.JPG  
  inflating: volumes/patient_159/Axial/I00043.JPG  
  inflating: volumes/patient_159/Axial/I00046.JPG  
  inflating: volumes/patient_159/Axial/I00052.JPG  
  inflating: volumes/patient_159/Axial/I00051.JPG  
  inflating: volumes/patient_159/Axial/I00049.JPG  
  inflating: volumes/patient_159/Axial/I00050.JPG  
  inflating: volumes/patient_159/Axial/I00036.JPG  
  inflating: volumes/patient_159/Axial/I00042.JPG  
  inflating: volumes/patient_159/Axial/I00044.JPG  
  inflating: volumes/patient_159/Axial/I00037.JPG  
  inflating: volumes/patient_159/Axial/I00038.JPG  
   creating: volumes/patient_160/
   creating: volumes/patient_160/Axial/
  inflating: volumes/patient_160/Axial/I00015.JPG  
  inflating: volumes/patient_160/Axial/I00001.JPG  
  inflating: volumes/patien

CT COVID R

In [ ]:
!wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1-NcbKPvATbRLqFGa-_rZvNCgaFiLEGO-' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1-NcbKPvATbRLqFGa-_rZvNCgaFiLEGO-" -O archivo.zip && rm -rf /tmp/cookies.txt
!unzip archivo.zip

--2020-04-29 21:52:10--  https://docs.google.com/uc?export=download&confirm=QwNs&id=1-NcbKPvATbRLqFGa-_rZvNCgaFiLEGO-
Resolving docs.google.com (docs.google.com)... 173.194.203.102, 173.194.203.139, 173.194.203.113, ...
Connecting to docs.google.com (docs.google.com)|173.194.203.102|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://doc-08-9s-docs.googleusercontent.com/docs/securesc/djvlrjc9dh0dn3povon7an80fn2mm12i/ik17n6r7g3mblp3d7vn7jt5649jl0u25/1588197075000/11546061572946484211/04901204028760357803Z/1-NcbKPvATbRLqFGa-_rZvNCgaFiLEGO-?e=download [following]
--2020-04-29 21:52:10--  https://doc-08-9s-docs.googleusercontent.com/docs/securesc/djvlrjc9dh0dn3povon7an80fn2mm12i/ik17n6r7g3mblp3d7vn7jt5649jl0u25/1588197075000/11546061572946484211/04901204028760357803Z/1-NcbKPvATbRLqFGa-_rZvNCgaFiLEGO-?e=download
Resolving doc-08-9s-docs.googleusercontent.com (doc-08-9s-docs.googleusercontent.com)... 74.125.20.132, 2607:f8b0:400e:c07::84
Connect

RX COVID R

In [ ]:
!wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1Tjg_mI4n-TNWG2uM6IC9KfrdUVgWLFTG' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1Tjg_mI4n-TNWG2uM6IC9KfrdUVgWLFTG" -O archivo.zip && rm -rf /tmp/cookies.txt
!unzip archivo.zip

--2020-06-08 14:53:45--  https://docs.google.com/uc?export=download&confirm=2d0_&id=1Tjg_mI4n-TNWG2uM6IC9KfrdUVgWLFTG
Resolving docs.google.com (docs.google.com)... 108.177.15.101, 108.177.15.138, 108.177.15.113, ...
Connecting to docs.google.com (docs.google.com)|108.177.15.101|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://doc-10-c8-docs.googleusercontent.com/docs/securesc/33kkc6lik7ph39gvcv8icvg5dm402go9/5aeed93tsqd3bpejlcb6jo2nbnvt9vfl/1591628025000/11546061572946484211/07746778656922500181Z/1Tjg_mI4n-TNWG2uM6IC9KfrdUVgWLFTG?e=download [following]
--2020-06-08 14:53:45--  https://doc-10-c8-docs.googleusercontent.com/docs/securesc/33kkc6lik7ph39gvcv8icvg5dm402go9/5aeed93tsqd3bpejlcb6jo2nbnvt9vfl/1591628025000/11546061572946484211/07746778656922500181Z/1Tjg_mI4n-TNWG2uM6IC9KfrdUVgWLFTG?e=download
Resolving doc-10-c8-docs.googleusercontent.com (doc-10-c8-docs.googleusercontent.com)... 74.125.140.132, 2a00:1450:400c:c08::84
Connecting

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


# SUPERVISADO 2

In [ ]:
%tensorflow_version 2.x

In [ ]:
import tensorflow as tf
import sklearn
import os
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix, multilabel_confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Dense, Activation, Flatten, Dropout, GlobalAveragePooling2D
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras import regularizers
import matplotlib.pyplot as plt
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import SGD, Adam, RMSprop
from tensorflow.keras.preprocessing import image
from sklearn.metrics import plot_confusion_matrix

## COVID RX, CT

### Crear los dataframes

In [ ]:
dataset = 'RX_COVID_19_R'
dataset_base = 'covid19_rx'

In [ ]:
def dataset_covid19(dataset):
    if dataset == 'RX_COVID_19_R':
        ruta_data_split = '/content/COVID-19 Radiography Database/data_split/'
        ruta_datos = '/content/COVID-19 Radiography Database/'
        df_train=pd.read_csv(ruta_data_split+'train_fold1.txt',names=['filename'])
        df_train['clase']=df_train['filename'].apply(lambda x:x.split('/')[0])
        df_train['filename']=df_train['filename'].apply(lambda x:ruta_datos+x)

        df_test=pd.read_csv(ruta_data_split+'test_fold1.txt',names=['filename'])
        df_test['clase']=df_test['filename'].apply(lambda x:x.split('/')[0])
        df_test['filename']=df_test['filename'].apply(lambda x:ruta_datos+x)

        df_val = pd.DataFrame(columns=['filename','clase'])

    elif dataset == 'RX_COVID_19_F':
        ruta_data_split = '/content/RX_COVID-19_F/data_split/frontal/'
        ruta_datos = '/content/RX_COVID-19_F/'
        df_train=pd.read_csv(ruta_data_split+'train_fold1.txt',names=['filename'])
        df_train['clase']=df_train['filename'].apply(lambda x:x.split('/')[0])
        df_train['filename']=df_train['filename'].apply(lambda x:ruta_datos+x)

        df_test=pd.read_csv(ruta_data_split+'test_fold1.txt',names=['filename'])
        df_test['clase']=df_test['filename'].apply(lambda x:x.split('/')[0])
        df_test['filename']=df_test['filename'].apply(lambda x:ruta_datos+x)

    return df_train ,df_test

if dataset == 'CT_COVID_19_R':
        ruta_data_split = '/content/CT_COVID-19_R_slides/data_split/'
        ruta_datos = '/content/CT_COVID-19_R_slides/'
        df_train_covid=pd.read_csv(ruta_data_split+'train_CT_COVID.txt',names=['filename'])
        df_train_covid['filename']=["/".join(['CT_COVID',i]) for i in df_train_covid.filename.values]
        df_train_noncovid=pd.read_csv(ruta_data_split+'train_CT_nonCOVID.txt',names=['filename'])
        df_train_noncovid['filename']=["/".join(['CT_NonCOVID',i]) for i in df_train_noncovid.filename.values]
        frames = [df_train_covid, df_train_noncovid]
        df_train = pd.concat(frames)

        df_val_covid=pd.read_csv(ruta_data_split+'val_CT_COVID.txt',names=['filename'])
        df_val_covid['filename']=["/".join(['CT_COVID',i]) for i in df_val_covid.filename.values]
        df_val_noncovid=pd.read_csv(ruta_data_split+'val_CT_nonCOVID.txt',names=['filename'])
        df_val_noncovid['filename']=["/".join(['CT_NonCOVID',i]) for i in df_val_noncovid.filename.values]
        frames = [df_val_covid, df_val_noncovid]
        df_valid = pd.concat(frames)

        df_test_covid=pd.read_csv(ruta_data_split+'test_CT_COVID.txt',names=['filename'])
        df_test_covid['filename']=["/".join(['CT_COVID',i]) for i in df_test_covid.filename.values]
        df_test_noncovid=pd.read_csv(ruta_data_split+'test_CT_nonCOVID.txt',names=['filename'])
        df_test_noncovid['filename']=["/".join(['CT_NonCOVID',i]) for i in df_test_noncovid.filename.values]
        frames = [df_test_covid, df_test_noncovid]
        df_test = pd.concat(frames)

        df_train['clase']=df_train['filename'].apply(lambda x:x.split('/')[0])
        df_train['filename']=df_train['filename'].apply(lambda x:ruta_datos+x)

        df_test['clase']=df_test['filename'].apply(lambda x:x.split('/')[0])
        df_test['filename']=df_test['filename'].apply(lambda x:ruta_datos+x)

        df_valid['clase']=df_valid['filename'].apply(lambda x:x.split('/')[0])
        df_valid['filename']=df_valid['filename'].apply(lambda x:ruta_datos+x)


In [ ]:
if dataset == 'RX_COVID_19_R' or dataset == 'RX_COVID_19_F':
    df_train, df_test = dataset_covid19(dataset)

In [ ]:
# extraer el validacion de train
if dataset == 'RX_COVID_19_R' or dataset == 'RX_COVID_19_F':
    df_train1, df_valid = train_test_split(df_train, test_size=0.2)

In [ ]:
df_train.groupby('clase').count()

filename
clase                   
NORMAL               939
covid                153
viralpneumonia       941

In [ ]:
df_valid.groupby('clase').count()

filename
clase                   
NORMAL               198
covid                 29
viralpneumonia       180

In [ ]:
df_test.groupby('clase').count()

filename
clase                   
NORMAL               402
covid                 66
viralpneumonia       404

### Crear el modelo base con transfer learning

In [ ]:
def transfer_learning(base_model, num_clases, activacion_final):
    x = base_model.output
    x = GlobalAveragePooling2D()(x)
    x = Dense(1024, activation='relu')(x)
    x = Dropout(0.5)(x)
    predictions = Dense(num_clases, activation=activacion_final)(x)
    model = Model(inputs=base_model.input, outputs=predictions)

    # Descongelado total
    for layer in base_model.layers[:27]:
        layer.trainable = False
    for layer in base_model.layers[27:]:
        layer.trainable = True
    return model

def make_model(arquitectura, HEIGHT, WIDTH):
    if arquitectura == 'InceptionV3':
        from tensorflow.keras.applications.inception_v3 import InceptionV3, preprocess_input
        base_model = InceptionV3(weights='imagenet',include_top=False,input_shape=(HEIGHT, WIDTH, 3))
    elif arquitectura == 'InceptionV4':
        from tensorflow.keras.applications.inception_resnet_v2 import InceptionResNetV2, preprocess_input
        base_model = InceptionResNetV2(weights='imagenet',include_top=False,input_shape=(HEIGHT, WIDTH, 3))
    elif arquitectura == 'ResNet152':
        from tensorflow.keras.applications.resnet import ResNet152, preprocess_input
        base_model = ResNet152(weights='imagenet',include_top=False,input_shape=(HEIGHT, WIDTH, 3))
    return base_model, preprocess_input


## Generadores de imagenes y de entrenamiento

In [ ]:
def make_generator(df_train, df_val, df_test, HEIGHT,WIDTH, tipo, preprocess_input):
    # Generador de imagenes y archivos para train
    datagen = ImageDataGenerator(preprocessing_function=preprocess_input,
                                 rotation_range=40,
                                 width_shift_range=0.1,
                                 height_shift_range=0.1,
                                 shear_range=0.01,
                                 zoom_range=[0.9, 1.25],
                                 horizontal_flip=True,
                                 vertical_flip=False,
                                 fill_mode='reflect',
                                 data_format='channels_last'
                                )
    train_generator = datagen.flow_from_dataframe(
                         dataframe=df_train,
                         x_col=x_col_name,
                         y_col=y_col_name,
                         target_size=(HEIGHT,WIDTH),
                         class_mode=tipo,
                         batch_size=batch_size,
                         seed=42,
                         shuffle=True)
    # Generador de imagenes y archivos para validacion
    val_datagen=ImageDataGenerator(preprocessing_function=preprocess_input)
    valid_generator=val_datagen.flow_from_dataframe(
                        dataframe=df_val,
                        x_col=x_col_name,
                        y_col=y_col_name,
                        batch_size=batch_size,
                        seed=42,
                        shuffle=True,
                        class_mode=tipo,
                        target_size=(HEIGHT,WIDTH))
    # Generador de imagenes y archivos para test
    test_datagen=ImageDataGenerator(preprocessing_function=preprocess_input)
    test_generator=test_datagen.flow_from_dataframe(
                        dataframe=df_test,
                        x_col=x_col_name,
                        y_col=y_col_name,
                        batch_size=batch_size,
                        seed=42,
                        shuffle=False,
                        class_mode=tipo,
                        target_size=(HEIGHT,WIDTH))

    return train_generator, valid_generator, test_generator

## Entrenamiento

In [ ]:
def train(arquitectura, df_train, df_val, df_test, lr, train_epochs, batch_size,
          loss, tipo, clases, augmenting_factor, activacion_final):

    base_model, preprocess_input = make_model(arquitectura, HEIGHT, WIDTH)
    # realizar el llamado a trasfer learning
    finetune_model = transfer_learning(base_model,clases, activacion_final)

    # crear generadores
    train_generator, valid_generator, test_generator = make_generator(df_train, df_val, df_test, HEIGHT,WIDTH, tipo, preprocess_input)

    # definir pasos de iteracion para cada conjunto de datos
    NUM_EPOCHS = train_epochs
    num_train_images = len(df_train)*augmenting_factor
    STEP_SIZE_TRAIN=num_train_images//train_generator.batch_size
    STEP_SIZE_VALID=valid_generator.n//valid_generator.batch_size
    STEP_SIZE_TEST=test_generator.n//test_generator.batch_size

    # callbacks
    generator_seguimiento = valid_generator
    pasos_seguimiento = STEP_SIZE_VALID
    early = EarlyStopping(monitor='val_loss', min_delta=1e-3, patience=5, verbose=1,restore_best_weights=True)

    # Compilar y Entrenamiento
    solver = Adam(lr=lr)

    if num_clases>2:
        metrics = ['accuracy', tf.keras.metrics.AUC(name='auc', multi_label=True)]
        # calcular pesos de cada clase
        total = df_train.shape[0]
        classes = df_train.groupby('clase').count().index.values
        weights = (total/df_train.groupby('clase').count().values)/3
        # rx normal:0, covid:1, pneumonia:2
        class_weight = {0:weights[0][0], 1:weights[1][0], 2:weights[2][0]}

    else:
        metrics = ['binary_accuracy', tf.keras.metrics.AUC(name='auc', multi_label=False)]
        # calcular pesos de cada clase
        total = df_train.shape[0]
        classes = df_train.groupby('clase').count().index.values
        weights = (total/df_train.groupby('clase').count().values)/2
        # ct covid:0, no covid:1
        class_weight = {0:weights[0][0], 1:weights[1][0]}

    finetune_model.compile(solver, loss=loss, metrics=metrics)

    history = finetune_model.fit(
                train_generator,
                epochs=NUM_EPOCHS, workers=1,
                steps_per_epoch=STEP_SIZE_TRAIN,
                validation_data=generator_seguimiento,
                validation_steps=pasos_seguimiento,
                callbacks=[],
                class_weight=class_weight)

    score0=finetune_model.evaluate(train_generator,verbose=1,steps=STEP_SIZE_TRAIN)
    score1=finetune_model.evaluate(valid_generator,verbose=1,steps=STEP_SIZE_VALID)
    score2=finetune_model.evaluate(test_generator,verbose=1,steps=STEP_SIZE_TEST)

    return finetune_model, history, train_generator, valid_generator, test_generator

In [ ]:
HEIGHT, WIDTH = 255,255
num_clases = 3
arquitectura = 'ResNet152'
activacion_final = 'softmax'
x_col_name = 'filename'
y_col_name = 'clase'
tipo = 'categorical'
batch_size = 16
augmenting_factor = 2
train_epochs = 20
lr=0.00001
loss='categorical_crossentropy'

In [ ]:
np.random.seed(42)
tf.random.set_seed(42)
tf.keras.backend.clear_session()

finetune_model, history, train_generator, valid_generator, test_generator = train(arquitectura, df_train, df_valid, df_test, lr,
                                train_epochs, batch_size, loss, tipo, num_clases, augmenting_factor, activacion_final)

Found 2033 validated image filenames belonging to 3 classes.
Found 407 validated image filenames belonging to 3 classes.
Found 872 validated image filenames belonging to 3 classes.
Epoch 1/20
54/54 [==============================] - 21s 389ms/step - loss: 0.4064 - accuracy: 0.8449 - auc: 0.9648


In [ ]:
#Confution Matrix and Classification Report
logits = finetune_model.predict_generator(test_generator, df_test.shape[0] // batch_size+1)
y_pred_class = np.argmax(logits, axis=1)
predicted_class_probab=np.max(logits,axis=1)
print('Confusion Matrix')
print(confusion_matrix(test_generator.classes, y_pred_class))
print('Classification Report')
if num_clases == 2:
    target_names = [ 'Covid', 'no Covid']
else:
  target_names = ['Normal', 'Covid', 'Pneumonia']
print(classification_report(test_generator.classes, y_pred_class, target_names=target_names))

Instructions for updating:
Please use Model.predict, which supports generators.
Confusion Matrix
[[400   0   3]
 [  0  61   1]
 [ 35   0 369]]
Classification Report
              precision    recall  f1-score   support

      Normal       0.92      0.99      0.95       403
       Covid       1.00      0.98      0.99        62
   Pneumonia       0.99      0.91      0.95       404

    accuracy                           0.96       869
   macro avg       0.97      0.96      0.97       869
weighted avg       0.96      0.96      0.96       869



In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [ ]:
!cp /content/RX_COVID-19_F/red_1_3.h5 /content/drive/My\ Drive/Datos/Investigación/Proyectos/Proyecto\ DeepSars/DeepSARS_Data/saved_models

In [ ]:
tf.keras.models.save_model(
    finetune_model, '/content/RX_COVID-19_F/red_1_3.h5', overwrite=True, include_optimizer=True, save_format='h5',
)


In [ ]:
import gc
from tensorflow.keras.models import Model
from tensorflow.keras.backend import clear_session

def reset_keras():
    # Reset Keras Session
    clear_session()
    print(gc.collect())
reset_keras()

697


In [ ]:
!nvidia-smi

Thu Apr 23 13:38:41 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64.00    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   71C    P0    90W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

Modelo Red1.h5

Es una red pre-entrenada InceptionV3 con las 27 primeras capas congeladas y un lr 0.00001 y optimizador adam. Además, aumento de datos usando como rotaciones, flip, shitf, ... un factor de aumento de 2 y balanceo usando diccionario de pesos, en el top de la capa se agrego un global pooling, densa de 1024 y dropout de 0.5. (7 epochs) fold 1.

Este modelo en RX_COVID_F obtuvo la siguiete matrix de confuision:  
[[393   0  10]  
 [  2  60   0]  
 [ 39   0 365]]  

Este modelo en RX_COVID_R obtuvo la siguiente matrix de confusion:  
[[393   0   9]  
 [  0  66   0]  
 [ 39   2 363]]  

Este modelo en CT_COVID_R obtuvo la siguiente matrix de confusion (10 epochs y factor de aumento de 3):    
[[76 22]  
 [13 92]]      


In [ ]:
!cp /content/RX_COVID-19_F/red_1_3.h5 /content/drive/My\ Drive/Datos/Investigación/Proyectos/DeepSARS_Data/saved_models